import Head from 'next/head'
import styles from '../styles/fonts-test.module.css'

export default function FontsTest() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Fonts Test Page</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main>
        <h1>Hello Font Heads!</h1>
      </main>
    </div>
  )
}