import Head from 'next/head'

export default function Tester() {
  return (
    <div>
      <Head>
        <title>Tester Page</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main>
        <h1>Hello</h1> 
      </main>
    </div>
  )
}
